movie_project/movie_app/urls.py
from django.urls import path

from movie_app import views

app_name = 'movie_app'  # name_space

urlpatterns = [

    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add', views.add, name='add'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

movie_project/movie_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_project/movie_app/models.py
from django.db import models


# Create your models here.

class Movies(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movie_project/movie_app/forms.py
from django import forms

from movie_app.models import Movies


class Movieform(forms.ModelForm):
    class Meta:
        model = Movies
        fields = ['name', 'desc', 'year', 'img']

movie_project/movie_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import Movieform
from .models import Movies


# Create your views here.
def index(request):
    movie = Movies.objects.all()
    context = {'movie_list': movie}
    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie = Movies.objects.get(id=movie_id)
    return render(request, 'Detail.html', {'movie': movie})


def add(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        description = request.POST.get("desc")
        year = request.POST.get("year")
        image = request.FILES['img']
        movie = Movies(name=name, desc=description, year=year, img=image)
        movie.save()
    return render(request, 'add.html')

def update(request, id):
    movie = Movies.objects.get(id=id)
    form = Movieform(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'update.html', {'form': form, 'movie': movie})

def delete(request, id):
    if request.method == 'POST':
        movie = Movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movie_project/templates/Delete.html
{% extends 'base.html'%}
{% block body %}

<form method="post">
  {% csrf_token %}
  <h2>Are you sure , do you want to delete the item</h2>
  <input type="submit" class="btn btn-danger">
</form>
{% endblock %}

movie_project/templates/Detail.html
{% extends 'base.html'%}
{% block body %}



<div class="card mb-3">
  <img src="{{ movie.img.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ movie.name }} </h5>
    <p class="card-text">{{ movie.desc }}</p>
    <p class="card-text"><small class="text-muted">{{ movie.year }}</small></p>
    <a href="{% url 'movie_app:update' movie.id %}" class="btn btn-primary">update</a>
    <a href="{% url 'movie_app:delete' movie.id %}" class="btn btn-danger">delete</a>
  </div>
</div>




{% endblock %}

movie_project/templates/add.html
{% extends 'base.html'%}
{% block body %}

<div class="container mt-5">

    <form id="productForm" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label for="productName">Product Name</label>
        <input type="text" class="form-control" id="productName" name="name" required>
      </div>
      <div class="form-group">
        <label for="productDescription">Product Description</label>
        <textarea class="form-control" id="productDescription" name="desc" rows="3" required></textarea>
      </div>
      <div class="form-group">
        <label for="productYear">Year</label>
        <input type="number" class="form-control" id="productYear" name="year" required>
      </div>
      <div class="form-group">
        <label for="productImage">Product Image</label>
        <input type="file" class="form-control" id="productImage" name="img"  required>
      </div>
      <button type="submit" class="btn btn-primary">Add Product</button>
         </form>
  </div>


        {% endblock %}

movie_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies</title>
    <style>

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            padding: 8px;
            text-align: center;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>

<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">

      <img src="https://asset.brandfetch.io/id4J58sqa_/idASFvdnzd.png" alt="" width="40" height="34" class="d-inline-block align-text-top">
      Movie App
    </a>
      <a href="add" class="btn btn-info">add</a>
  </div>
  </div>
</nav>
<div class="container">

{% block body %}
{% endblock %}

    </div>

</body>
</html>


</body>
</html>

movie_project/templates/index.html
{% extends 'base.html'%}
{% block body %}

{% for i in movie_list %}
<div class="poster">
<div class="card" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ i.name }}</h5>

    <a href="{% url 'movie_app:detail' i.id %}" class="btn btn-primary">Details</a>
  </div>
</div>
  </div>
{% endfor %}
{% endblock %}

movie_project/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>update</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
</body>
</html>